# Tarea 2 Parte 2

In [83]:
import numpy as np

## Ejercicio 1

En ML usamos la entropía cruzada como una forma de medir que tan bueno es un modelo de variables discretas a través de comparar la distribución de probabilidad que el modelo produce o predice, vs la distribución de probabilidad real dada por los datos de entrenamiento.

Podemos ver el siguiente ejemplo que define la forma en que se calcula la entropía cruzada y nos muestra un caso específico:

<img src="https://image.slidesharecdn.com/publishintroductiontodeeplearninginpythonandmatlab1-160502102437/95/introduction-to-deep-learning-in-python-and-matlab-54-638.jpg?cb=1462185644">

En este caso interpretamos así: El problema consiste en un modelo o algoritmo de ML que debe producir un vector de 3 elementos indicando la probabilidad de que ciertos datos X pertenezcan a una de 3 categorías.

* El modelo de ML produce un vector que indica que estima un 70% de probabilidad de que se trate de la categoría 0, 20% de probabilidad de que se trate de la categoría 1 y 10% de que se trate de la categoría 2.
* Los datos reales nos dicen que se trataba de un caso donde con total certeza se sabe que se trata de la categoría 0
* La entropía cruzada(a calcular en el ejercicio) nos indica que tan buena es la estimación del modelo, una EC de 0 es un modelo perfecto(en este caso un modelo que predice 100% de prob para la clase 0)

**Nota** 
* Aun que para calcular la entropía usamos logaritmos en base 2, en ML para calcular la entropía cruzada se usa logaritmo natural ya que con este se cumple el proposito **estimar que tanto se alejan las predicciones del modelo de ML de los datos reales** y es comun]mente mas rápido de calcular en la computadora.
* Ya que estamos trabajando con vectores que representan distribuciones de probabilidad , podemos toparnos con lo que se conoce como : **sparse vectors**(vectores donde la mayoría de elementos son 0), esto puede producir problemas ya que le logaritmo de 0 no esta definido, tu solución debe tomar en cuenta esto y evitar que devuelva "nan"

In [84]:
def cross_entropy(Y,Y_hat):
    # Ignora los mismos valores que son menores o iguales a cero. Exactamente las mismas posiciones en ambos arreglos,
    # de esa manera hay concordancia en la multiplicación de las matrices y no se calcula un logaritmo que de error
    Y     = Y[Y_hat > 0]
    Y_hat = Y_hat[Y_hat > 0]
    
    return -1 * np.sum((Y * np.log(Y_hat)))

y  = np.array([1.0,0,0])
y_hat = np.array([0.7,0.2,0.1])

cross_entropy(y,y_hat)


0.35667494393873245


# Magnitud de un Vector(norma o módulo)
 

Matemáticamente la magnitud de un vector(también conocida como norma vectorial)  nos indica  el tamaño de este , y nos sirve para tener una noción de la distancia desde un punto de referencia(origen) hasta el punto representado por el vector.


## Ejercicio 2
Crear una función que reciba como parámetro un vector x y calcule su magnitud o norma(euclidiana o L2) ,luego usarla para evaluar 2 vectores que representan los errores generados por 2 modelos de machine learning y concluir cual de los 2 modelos es mejor.

In [85]:
def magnitud(x):
    ## tu codigo aqui (~ 1 linea de codigo)
    return np.linalg.norm(x)
    
errores_modelo1 = np.array([1,2,1,2])
errores_modelo2 = np.array([0,1,1,2])

print(magnitud(errores_modelo1))
print(magnitud(errores_modelo2))

3.1622776601683795
2.449489742783178


## Ejercicio 3
Usando la función del ejercicio anterior, crea otra función normalizar(x) que reciba de parámetro un vector x aplique normalización sobre este, el resultado debe ser un nuevo vector del tamaño de x cuya magnitud es igual a 1.0

In [86]:
def normalizar(x):
    ## tu codigo aqui (~ 3 linea de codigo)
    return x/magnitud(x)

print(magnitud(normalizar(errores_modelo1)))
print(normalizar(errores_modelo2))

1.0
[0.         0.40824829 0.40824829 0.81649658]


# Producto Punto(escalar,interno,interior) y Ortogonalidad



## Ejercicio 4
### Aplicado en DS

Se tiene una red neuronal sencilla(y simplificada) como la de la siguiente imagen:
<img src="https://www.oreilly.com/library/view/practical-convolutional-neural/9781788392303/assets/246151fb-7893-448d-b9bb-7a87b387a24b.png">

Donde:
* INPUT LAYER: un vector X de tamaño = 2 que representa los datos de entrada
* HIDDEN_LAYER :capa oculta con 2 neuronas definidas por los vectores:
    * HL1 = [0.25,0.37]
    * HL2 = [-8,14]
* OUTPUT_LAYER = capa de salida definida por el vector [4,9]

Crear una funcion `neural_network(X)` para calcular:
* Calcule la salida de cada neurona en la capa intermedia aplicada a la capa de entrada.
* Use el resultado del paso anterior como entrada para la neurona en la capa de salida

Asumiendo que cada neurona identifica la similitud entre su entrada y la caracteística que representa concluir:
* Para cada vector de entrada Xi , cual neurona intermedia busca la característica que mas se parece a X.
* Cual vector de entrada Xi produce una activación alta(salida alta) en la capa de salida.

In [87]:
# Aplicar la red neuronal sobre los siguientes datos X
X1 = np.array([0.50,0.72])
X2 = np.array([-4,7])
X3 = np.zeros_like(X2)
X4 = np.ones_like(X1)
X5 = np.random.randn(X1.shape[0])

In [89]:
## tu codigo aqui:
def neural_network(X):
    HL1 = np.array([0.25,0.37])
    HL2 = np.array([-8,14])
    O_L = np.array([4,9])
    
    Hidden_Layer_1 = np.dot(X, HL1)
    Hidden_Layer_2 = np.dot(X, HL2)
    
    print("Hidden_Layer_1:", Hidden_Layer_1)
    print("Hidden_Layer_2:", Hidden_Layer_2)
    
    Final_Output = np.dot(np.array([Hidden_Layer_1, Hidden_Layer_2]), O_L)
    
    return Final_Output

print("Final Output X1:", neural_network(X1), "\n")
print("Final Output X2:", neural_network(X2), "\n")
print("Final Output X3:", neural_network(X3), "\n")
print("Final Output X4:", neural_network(X4), "\n")
print("Final Output X5:", neural_network(X5), "\n")

print("CONCLUSIONES:")
print("1. La neurona intermedia que busca la característica que más se parece a X es HL1.")
print("2. El vector X2 produce la activación más alta en la capa de salida.")

Hidden_Layer_1: 0.39139999999999997
Hidden_Layer_2: 6.08
Final Output X1: 56.2856 

Hidden_Layer_1: 1.5899999999999999
Hidden_Layer_2: 130
Final Output X2: 1176.36 

Hidden_Layer_1: 0.0
Hidden_Layer_2: 0
Final Output X3: 0.0 

Hidden_Layer_1: 0.62
Hidden_Layer_2: 6.0
Final Output X4: 56.48 

Hidden_Layer_1: -0.2801928973103335
Hidden_Layer_2: -7.75150528103829
Final Output X5: -70.88431911858594 

CONCLUSIONES:
1. La neurona intermedia que busca la característica que más se parece a X es HL1.
2. El vector X2 produce la activación más alta en la capa de salida.


## Ejercicio 5 (aplicado en DS)
La correlación cruzada es una medida de similitud entre 2 funciones como resultado de "desplazar" una sobre la otra, comunmente es usada para encontrar características relevantes en una función desconocida o no controlada.

En procesamiento de señales por ejemplo es usada para buscar y/o filtrar en una señal que varia en el tiempo cierta caracaterística de interés. Aveces es llamada también "sliding dot product" consiste en aplicar en cada punto de una función F el producto punto con cierta función G(comunmente mas corta) y luego "deslizar" G a un nuevo punto de la función, el resultado es una nueva función H que se interpreta como :**cuanto se parece** en cada punto la función F a la característica G. 

<img src="https://i.makeagif.com/media/11-25-2015/LZ9Ufj.gif"  height="250" width="300">

En este ejercicio usamos correlación cruzada para calcular las medias moviles promediando 3 puntos que ya vimos en otro ejemplo:

El primer paso es definir la función G que define el "filtro" a aplicar, para este caso consiste simplemente en un vector con 3 elementos donde cada elemento corresponde a 1/3, luego debemos aplicar el producto punto sobre cada punto de la función o datos originales(en este ejemplo llamados x) a traves aplicar el producto punto en cada elemento "corriendolo" de uno en uno

In [90]:
ruido = 0.1*np.random.randn(15) #el ruido comunmente se debe a aleatoriedad o captura no exacta de info.
x = np.linspace(0,2*np.pi,15) + ruido
x = np.sin(x)

filtro = np.array([1/3,1/3,1/3])

## tu codigo aqui (~ 3 linea de codigo)
suma_total = 0
for i in range(0,(len(x) - len(filtro))):
    suma_total += np.dot(filtro, x[i:i+3])

print(suma_total)

0.5064026989874582


# Operadores logicos en vectores

## Ejercicio 6
Dado el vector x, usar operadores lógicos sobre vectores y acceso a  elementos usando vectores booleanos , escribir un programa que calcule eun nuevo vector z conteniendo el valor absoluto de el vector x.

**Nota** No se puede usar np.abs() ni ciclos

**Tip** usar un vector booleano para saber que elementos son negativos y deben ser multiplicados por -1

In [91]:
x = np.linspace(-2,2,9)

# tu codigo aqui (~ 4 linea de codigo)
boolean_array = x < 0
vectorized_function = np.vectorize(lambda i: -1 if i == True else 1)
vectorized_function(boolean_array) * x


array([2. , 1.5, 1. , 0.5, 0. , 0.5, 1. , 1.5, 2. ])



## Ejercicio 7
Implementar la función:
$$h(x) = \begin{cases}0 & x< 0\\1 & 0<=x

$$h(x) = \begin{cases}0 & x< 0\\1 & 0<=x <=1\\0 & x> 1\end{cases}$$

Esta debe funcionar para vectores de cualquier tamaño x:

```
def h(x):
    
    ...
    
```
**nota** debe ser implementada sin ciclos o ifs 

In [92]:
def h(x):
    ## tu codigo aqui (~ 3 linea de codigo)
    condiciones = [x < 0, x > 1]
    resultados = [0, 0]
    return np.select(condiciones, resultados, 1)

x = np.array([0.1,-2,0.5,5])
print((h(x).astype(float)))

[1. 0. 1. 0.]


Para casos donde se requiere comportamiento parecido a este pero con mas condiciones, NumPy provee la función **np.select** , la descripción de esta función casi siempre es mas complicada de lo que debería y dificulta entenderla, vamos a buscar entenderla bajo un ejemplo.

Básicamente select se basa en :
* una lista de condiciones A
* una lista de valores a tomar según estas condiciones B
* un valor de  resultado default cuando ninguna de las condiciones en la  lista se cumple.
Estas 2 listas deben ser del mismo tamañaño.

# Select y performance

Usando select implementar una función k(x) con la siguiente definición:
$$k(x) = \begin{cases}-x & x< 0\\x^{3}  &0<=x<1\\x^{2}  &1<=x<2\\4  &otherwise\end{cases}$$



In [93]:
# Usando SELECT
def k_select(x):
    condiciones = [x < 0, (x >= 0)*(x < 1), (x >= 1)*(x < 2)]
    resultados = [-1*x, np.power(x,3), np.power(x,2)]
    return np.select(condiciones, resultados, 4)

# Vector de prueba - Exitoso
x = np.array([-10,0.5,1.5,5])
resultado = k_select(x)
print(resultado)

[10.     0.125  2.25   4.   ]


In [94]:
# Usando PIECEWISE
def k_piecewise(x):    
    return np.piecewise(x, [x < 0, (x >= 0)*(x < 1), (x >= 1)*(x < 2), x >= 2], [lambda i: -1*i, lambda i: np.power(i,3), lambda i: np.power(i,2), lambda i: 4])

# Vector de prueba - Exitoso
x = np.array([-10,0.5,1.5,5])
resultado = k_piecewise(x)
print(resultado)

[10.     0.125  2.25   4.   ]


Aun que select es muy conveniente y útil , no es la opción mas eficiente esto debido a que evalua todas las condiciones y todos los resultados, en programación en general buscamos escribir los programas de la manera mas eficiente posible y evitar calculos innecesarios, esto se vuelve vital en ciencia de datos cuando procesamos grandes volúmenes de información, por eso NumPy nos provee la alternativa a select llamada **piecewise** que funciona de manera similar .

Este funciona similar a select pero en vez de calcular todos los posibles resultados, calcula solo aquellos para los que la condición es True e ignora los False,sintácticamente piecewise requiere que los "resultados" sesan calcuados usando una lista de funciones por lo cual todos los resultados deben estar contenidos en una función  y el objeto función ser enviado a piecewise (si la función solo se utiliza una vez para este propósito, se puede usar funciones anónimas o lambda).

## Ejercicio 8

Investigar piecewise:
*  Usarlo para implementar la función anterior de manera eficiente
*  Usar piscewise para implementar la función:

$$m(x) = \begin{cases}e^{2x} & x< 0\\1  &0<=x<1\\e^{1-x}  &x>=1\\\end{cases}$$

Nuevamente, sin utilizar ciclos ni ifs

In [95]:
# Usando PIECEWISE - Ejercicio 2 - OJO: La última condición se cambió por x > 1 para definir los intervalos completos
def m(x):
    return np.piecewise(x, [x < 0, (x >= 0)*(x < 1), x >= 1], [lambda i: np.power(np.e, 2*i), lambda i: 1, lambda i: np.power(np.e, 1-i)])

# Vector de prueba - Exitoso
x = np.linspace(-10,10,20)
resultado = m(x)
print(resultado)

[2.06115362e-09 1.69205523e-08 1.38905265e-07 1.14030986e-06
 9.36110360e-06 7.68477620e-05 6.30863493e-04 5.17892437e-03
 4.25151525e-02 3.49018071e-01 1.00000000e+00 5.60488044e-01
 1.95620456e-01 6.82750741e-02 2.38292347e-02 8.31683351e-03
 2.90272519e-03 1.01310355e-03 3.53591445e-04 1.23409804e-04]
